package com.my.psremoteplay.feature.ps2.platform

import com.my.psremoteplay.core.streaming.Logger
import org.bytedeco.ffmpeg.global.avcodec
import org.bytedeco.ffmpeg.global.avutil
import org.bytedeco.javacv.FFmpegFrameGrabber
import org.bytedeco.javacv.FFmpegFrameRecorder
import org.bytedeco.javacv.Java2DFrameConverter
import java.awt.Rectangle
import java.awt.Robot
import java.awt.Toolkit

/**
 * Captures the screen using Java Robot, encodes to H.264 via JavaCV/FFmpeg,
 * and streams via RTP/UDP. Handles the entire server-side video pipeline.
 */
class JavaCvVideoStreamer(private val logger: Logger) {
    @Volatile private var streaming = false
    private var streamThread: Thread? = null

    fun start(rtpPort: Int) {
        if (streaming) return
        streaming = true

        streamThread = Thread {
            var recorder: FFmpegFrameRecorder? = null
            try {
                val robot = Robot()
                val screenSize = Toolkit.getDefaultToolkit().screenSize
                val captureRect = Rectangle(screenSize)
                val converter = Java2DFrameConverter()

                val width = 640
                val height = 448
                val fps = 30.0

                // RTP output URL — client connects to this
                val rtpUrl = "rtp://0.0.0.0:$rtpPort"

                recorder = FFmpegFrameRecorder(rtpUrl, width, height).apply {
                    format = "rtp"
                    videoCodec = avcodec.AV_CODEC_ID_H264
                    frameRate = fps
                    videoBitrate = 8_000_000 // 8 Mbps — plenty for 480p on LAN
                    setVideoOption("preset", "ultrafast")
                    setVideoOption("tune", "zerolatency")
                    setVideoOption("profile", "baseline")
                    gopSize = 60 // keyframe every 2 seconds
                    pixelFormat = avutil.AV_PIX_FMT_YUV420P

                    // Disable B-frames for minimum latency
                    setVideoOption("bf", "0")
                    setVideoOption("refs", "1")
                    setVideoOption("rc-lookahead", "0")

                    // RTP-specific: limit packet size for UDP
                    setOption("pkt_size", "1200")
                }

                recorder.start()
                logger.log("VIDEO", "RTP stream started on port $rtpPort (${width}x${height} H.264 @ ${fps}fps)")

                // Generate SDP for client connection
                val sdpFile = java.io.File(System.getProperty("java.io.tmpdir"), "ps2stream.sdp")
                // SDP will be auto-generated by FFmpeg at the RTP URL
                logger.log("VIDEO", "Clients connect to: rtp://SERVER_IP:$rtpPort")

                val frameIntervalMs = (1000.0 / fps).toLong()
                var frameCount = 0L

                while (streaming) {
                    val frameStart = System.currentTimeMillis()

                    val screenshot = robot.createScreenCapture(captureRect)
                    val scaled = java.awt.image.BufferedImage(width, height, java.awt.image.BufferedImage.TYPE_3BYTE_BGR)
                    val g = scaled.createGraphics()
                    g.drawImage(screenshot, 0, 0, width, height, null)
                    g.dispose()

                    val frame = converter.convert(scaled)
                    recorder.record(frame)
                    frameCount++

                    if (frameCount % 300 == 0L) {
                        logger.log("VIDEO", "Streamed $frameCount frames")
                    }

                    val elapsed = System.currentTimeMillis() - frameStart
                    val sleepTime = frameIntervalMs - elapsed
                    if (sleepTime > 0) Thread.sleep(sleepTime)
                }
            } catch (e: Exception) {
                if (streaming) {
                    logger.error("VIDEO", "Video streaming error: ${e.message}", e)
                }
            } finally {
                try { recorder?.stop() } catch (_: Exception) {}
                try { recorder?.release() } catch (_: Exception) {}
                logger.log("VIDEO", "Video stream stopped")
            }
        }.apply { isDaemon = true; name = "javacv-video-streamer"; start() }
    }

    fun stop() {
        streaming = false
        streamThread?.join(3000)
        streamThread = null
    }

    fun isStreaming(): Boolean = streaming && streamThread?.isAlive == true
}
